"""adds model for one line of eeo1 data.  database is called eeo1_db_development

Revision ID: c0bfcd9ea018
Revises: 
Create Date: 2023-01-26 10:16:59.136763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0bfcd9ea018'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eeo1_data_line',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('count_employees', sa.Integer(), nullable=False),
    sa.Column('job_category', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('race', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eeo1_data_line')
    # ### end Alembic commands ###
